version: '3.8'

services:
  afiagate-webapp:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
    networks:
      - afiagate-network

  # Optional: Add a reverse proxy with SSL
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - afiagate-webapp
    restart: unless-stopped
    networks:
      - afiagate-network

networks:
  afiagate-network:
    driver: bridge

volumes:
  logs:
  ssl:

